import { ACCENT, ACCENT_SOFT, INK, PAPER, LINE, MUTED, RED, GREEN } from './theme.js';


export const styles = {
  app: { maxWidth: 480, margin: "0 auto", minHeight: "100vh", background: PAPER, color: INK, fontFamily: "var(--font)", fontSize: "var(--base-size)", letterSpacing: "var(--tracking)", position: "relative", paddingBottom: 76, WebkitFontSmoothing: "antialiased" },
  header: { position: "sticky", top: 0, zIndex: 5, background: PAPER, padding: "14px 18px 10px", borderBottom: `1px solid ${LINE}` },
  brandRow: { display: "flex", justifyContent: "space-between", alignItems: "baseline" },
  brand: { fontSize: 15, fontWeight: 800, letterSpacing: "0.05em" },
  cloud: { fontSize: 11, color: MUTED },
  monthPicker: { display: "flex", alignItems: "center", justifyContent: "center", gap: 4, marginTop: 8 },
  monthArrow: { border: "none", background: "transparent", color: ACCENT, fontSize: 24, width: 36, height: 36, cursor: "pointer" },
  monthSelect: { border: "none", background: "transparent", fontSize: 19, fontWeight: 800, textAlign: "center", color: INK, appearance: "none", WebkitAppearance: "none", textAlignLast: "center", cursor: "pointer", fontFamily: "inherit" },
  main: { padding: "12px 16px" },
  heroCard: { background: "var(--hero-bg)", borderRadius: "var(--radius)", padding: "20px 20px 18px", color: "var(--hero-text)", boxShadow: "0 8px 24px rgba(47,111,91,0.22)", marginBottom: 14 },
  heroLabel: { fontSize: 12, opacity: 0.85, letterSpacing: "0.08em" },
  heroValue: { fontSize: 34, fontWeight: "var(--heavy)", marginTop: 4, letterSpacing: "-0.02em", color: "var(--hero-text)" },
  heroSub: { fontSize: 12.5, opacity: 0.9, marginTop: 6 },
  sumGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10, marginBottom: 6 },
  sumCell: { background: "var(--card-bg)", border: `1px solid ${LINE}`, borderRadius: "var(--radius)", padding: "12px 14px" },
  sumCellLabel: { fontSize: 12, color: MUTED },
  sumCellValue: { fontSize: 18, fontWeight: "var(--heavy)", marginTop: 3, fontFamily: "var(--num-font)", fontVariantNumeric: "var(--num-variant)" },
  noteRow: { display: "flex", justifyContent: "flex-end", fontSize: 12, padding: "8px 4px 2px" },
  checkCard: { borderRadius: 12, padding: "11px 14px", marginTop: 12, lineHeight: 1.5 },
  sectionTitle: { fontSize: 13, fontWeight: 700, margin: "18px 4px 8px" },
  balCard: { background: "var(--card-bg)", border: `1px solid ${LINE}`, borderRadius: "var(--radius)", padding: "6px 14px" },
  balRow: { display: "flex", justifyContent: "space-between", alignItems: "center", padding: "9px 0" },
  balAcc: { fontSize: 14 },
  balVal: { fontSize: "var(--num-size)", fontWeight: 600, fontVariantNumeric: "var(--num-variant)", fontFamily: "var(--num-font)" },
  viewToggle: { display: "inline-flex", background: "var(--group-bg)", borderRadius: 10, padding: 3, marginBottom: 12 },
  viewToggleBtn: { border: "none", background: "transparent", padding: "6px 11px", borderRadius: 8, fontSize: 12.5, fontWeight: 700, color: MUTED, cursor: "pointer", fontFamily: "inherit", whiteSpace: "nowrap" },
  viewToggleActive: { background: "var(--card-bg)", color: ACCENT, boxShadow: "0 1px 3px rgba(0,0,0,0.2)" },
  detailHead: { display: "flex", justifyContent: "space-between", alignItems: "center", fontSize: 13.5, fontWeight: 800, color: ACCENT, margin: "0 4px 7px" },
  detailCard: { background: "var(--card-bg)", border: `1px solid ${LINE}`, borderRadius: "var(--radius)", padding: "4px 14px 8px" },
  detailRow: { display: "flex", justifyContent: "space-between", alignItems: "center", padding: "10px 0 6px" },
  editRow: { display: "flex", justifyContent: "space-between", alignItems: "center", width: "100%", padding: "12px 2px", background: "transparent", border: "none", borderBottom: `1px solid ${PAPER}`, cursor: "pointer", fontFamily: "inherit", textAlign: "left" },
  editRowRight: { display: "flex", alignItems: "center", gap: 6 },
  chev: { color: MUTED, fontSize: 18, lineHeight: 1 },
  detailSubHead: { display: "flex", justifyContent: "space-between", alignItems: "center", padding: "8px 2px 2px" },
  editSubRow: { display: "flex", justifyContent: "space-between", alignItems: "center", width: "100%", padding: "8px 2px 8px 22px", background: "var(--subtotal-bg)", border: "none", borderBottom: `1px solid ${PAPER}`, cursor: "pointer", fontFamily: "inherit", textAlign: "left" },
  itemRow: { display: "flex", justifyContent: "space-between", alignItems: "center", width: "100%", padding: "var(--row-pad) 2px", background: "transparent", border: "none", borderBottom: `1px solid ${PAPER}`, cursor: "pointer", fontFamily: "inherit", textAlign: "left" },
  itemRowLeft: { display: "flex", alignItems: "center", gap: 6 },
  chevSpacer: { display: "inline-block", width: 16 },
  subGroupHead: { display: "flex", justifyContent: "space-between", alignItems: "center", padding: "8px 2px 6px", fontSize: 12, fontWeight: 700, color: MUTED, borderBottom: `1px solid ${LINE}` },
  subGroupTotal: { fontSize: 13, fontWeight: 700, color: INK, fontVariantNumeric: "tabular-nums" },
  subtotalRow: { display: "flex", justifyContent: "space-between", alignItems: "center", padding: "10px 2px", marginTop: 2, borderTop: `1.5px solid ${LINE}`, fontSize: 13.5, fontWeight: 800, color: INK, fontVariantNumeric: "tabular-nums" },
  tdSubLabel: { fontWeight: 800, background: "var(--subtotal-bg)" },
  tdSubTotal: { fontWeight: 800, background: "var(--subtotal-bg)", borderLeft: `1px solid ${LINE}` },
  collapseRow: { display: "flex", justifyContent: "space-between", alignItems: "center", width: "100%", padding: "12px 2px", background: "transparent", border: "none", borderBottom: `1px solid ${PAPER}`, cursor: "pointer", fontFamily: "inherit", textAlign: "left" },
  countBadge: { fontSize: 11, color: MUTED, background: "var(--group-bg)", borderRadius: 6, padding: "1px 7px", fontWeight: 600 },
  listRow: { display: "flex", justifyContent: "space-between", alignItems: "center", width: "100%", padding: "var(--row-pad) 2px", background: "transparent", border: "none", borderBottom: `1px solid ${PAPER}`, cursor: "pointer", fontFamily: "inherit", textAlign: "left" },
  catTag: { fontSize: 10.5, fontWeight: 700, border: "1px solid", borderRadius: 5, padding: "1px 6px" },
  detailItem: { fontSize: 14 },
  detailTotal: { fontSize: "var(--num-size)", fontWeight: 700, fontVariantNumeric: "var(--num-variant)", fontFamily: "var(--num-font)" },
  chipRow: { display: "flex", flexWrap: "wrap", gap: 6, paddingBottom: 8 },
  chip: { border: `1px solid ${LINE}`, background: PAPER, borderRadius: 8, padding: "4px 9px", fontSize: 12, color: INK, cursor: "pointer", fontVariantNumeric: "tabular-nums", fontFamily: "inherit" },
  chipGhost: { border: "none", background: "transparent", color: MUTED, fontSize: 12, cursor: "pointer", padding: 0 },
  tableScroll: { overflowX: "auto", border: `1px solid ${LINE}`, borderRadius: 12, background: "var(--card-bg)", WebkitOverflowScrolling: "touch" },
  table: { borderCollapse: "collapse", fontSize: 12.5, fontVariantNumeric: "var(--num-variant)", fontFamily: "var(--num-font)", minWidth: "100%" },
  th: { padding: "8px 10px", fontSize: 11, fontWeight: 700, color: MUTED, background: "var(--th-bg)", borderBottom: `1px solid ${LINE}`, whiteSpace: "nowrap", textAlign: "right" },
  thSticky: { position: "sticky", left: 0, zIndex: 2, textAlign: "left", background: "var(--th-bg)", minWidth: 96 },
  thTotal: { borderLeft: `1px solid ${LINE}`, textAlign: "right" },
  td: { padding: "8px 10px", borderBottom: `1px solid ${PAPER}`, whiteSpace: "nowrap" },
  tdSticky: { position: "sticky", left: 0, background: "var(--card-bg)", zIndex: 1, fontWeight: 600, minWidth: 96, borderRight: `1px solid ${LINE}`, textAlign: "var(--label-align)" },
  tdNum: { padding: "6px 10px", borderBottom: `1px solid ${PAPER}`, textAlign: "var(--num-align)", whiteSpace: "nowrap", fontSize: "var(--num-size)" },
  tdTotalCell: { fontWeight: 700, borderLeft: `1px solid ${LINE}`, background: "var(--total-cell-bg)" },
  tdGroup: { padding: "6px 10px", fontSize: 11.5, fontWeight: 800, color: INK, position: "sticky", left: 0, background: "var(--group-bg)" },
  tdAcct: { padding: "5px 10px", fontSize: 11, fontWeight: 700, color: ACCENT, position: "sticky", left: 0, background: "var(--acct-bg)" },
  cellBtn: { border: "none", background: "transparent", color: "inherit", fontSize: 12.5, cursor: "pointer", fontVariantNumeric: "tabular-nums", padding: 0, minWidth: 20, fontFamily: "inherit" },
  debtSummary: { display: "flex", justifyContent: "space-between", alignItems: "center", background: "var(--card-bg)", border: `1px solid ${LINE}`, borderRadius: 14, padding: "12px 16px", marginBottom: 10 },
  cardListRow: { display: "flex", justifyContent: "space-between", alignItems: "center", width: "100%", padding: "12px 2px", borderBottom: `1px solid ${PAPER}`, background: "transparent", border: "none", cursor: "pointer", fontFamily: "inherit", textAlign: "left" },
  brandTag: { fontSize: 11, color: MUTED, border: `1px solid ${LINE}`, borderRadius: 6, padding: "3px 8px" },
  settingRow: { display: "flex", justifyContent: "space-between", alignItems: "center", padding: "11px 0", fontSize: 14, borderBottom: `1px solid ${PAPER}` },
  addBtn: { border: `1px solid ${ACCENT}`, background: ACCENT_SOFT, color: ACCENT, borderRadius: 8, padding: "5px 12px", fontSize: 12.5, fontWeight: 700, cursor: "pointer", fontFamily: "inherit" },
  removeBtn: { border: "none", background: "transparent", color: MUTED, fontSize: 12, cursor: "pointer" },
  backupBtn: { display: "block", width: "100%", border: `1px solid ${LINE}`, background: "var(--card-bg)", color: ACCENT, borderRadius: 10, padding: "11px", fontSize: 13.5, fontWeight: 700, cursor: "pointer", marginTop: 8, fontFamily: "inherit" },
  themeSection: { fontSize: 12.5, fontWeight: 800, color: ACCENT, margin: "18px 4px 7px" },
  navRow: { display: "flex", justifyContent: "space-between", alignItems: "center", width: "100%", padding: "14px 14px", marginBottom: 18, background: "var(--card-bg)", border: `1px solid ${LINE}`, borderRadius: "var(--radius)", cursor: "pointer", fontFamily: "inherit", textAlign: "left" },
  backLink: { border: "none", background: "transparent", color: ACCENT, fontSize: 14, fontWeight: 700, cursor: "pointer", padding: "2px 2px 10px", fontFamily: "inherit" },
  themeRow: { display: "flex", justifyContent: "space-between", alignItems: "center", padding: "10px 2px", borderBottom: `1px solid ${PAPER}` },
  themeLabel: { fontSize: 13.5 },
  colorInput: { width: 34, height: 26, border: `1px solid ${LINE}`, borderRadius: 6, padding: 0, background: "none", cursor: "pointer" },
  alignBtn: { border: `1px solid ${LINE}`, background: "var(--card-bg)", borderRadius: 7, padding: "5px 11px", fontSize: 12.5, cursor: "pointer", color: INK, fontFamily: "inherit" },
  alignBtnActive: { background: ACCENT, color: "#fff", border: `1px solid ${ACCENT}` },
  fab: { position: "fixed", right: "max(18px, calc(50% - 240px + 18px))", bottom: 90, width: 58, height: 58, borderRadius: "50%", background: ACCENT, color: "#fff", border: "none", boxShadow: "0 8px 22px rgba(47,111,91,0.4)", cursor: "pointer", zIndex: 6, display: "flex", alignItems: "center", justifyContent: "center" },
  tabs: { position: "fixed", bottom: 0, left: "50%", transform: "translateX(-50%)", width: "100%", maxWidth: 480, display: "flex", background: "var(--tab-bg)", borderTop: `1px solid ${LINE}`, zIndex: 6 },
  tabBtn: { flex: 1, border: "none", background: "transparent", padding: "9px 0 11px", display: "flex", flexDirection: "column", alignItems: "center", cursor: "pointer", fontFamily: "inherit" },
  sheetBackdrop: { position: "fixed", inset: 0, background: "rgba(28,35,33,0.35)", zIndex: 20, display: "flex", alignItems: "flex-end", justifyContent: "center" },
  sheet: { width: "100%", maxWidth: 480, background: PAPER, borderRadius: "20px 20px 0 0", padding: "10px 18px calc(20px + env(safe-area-inset-bottom))", maxHeight: "92vh", overflowY: "auto", animation: "slideUp 0.22s ease" },
  miniSheet: { width: "100%", maxWidth: 480, background: PAPER, borderRadius: "20px 20px 0 0", padding: "18px 18px calc(20px + env(safe-area-inset-bottom))", animation: "slideUp 0.22s ease" },
  sheetHandle: { width: 40, height: 4, borderRadius: 2, background: LINE, margin: "4px auto 12px" },
  sheetTitle: { fontSize: 16, fontWeight: 800, marginBottom: 14 },
  pickRow: { display: "flex", alignItems: "center", gap: 12, width: "100%", padding: "14px 4px", background: "transparent", border: "none", borderBottom: `1px solid ${LINE}`, cursor: "pointer", fontFamily: "inherit" },
  pickIcon: { width: 40, height: 40, borderRadius: 12, color: "#fff", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 18, flexShrink: 0 },
  kindRow: { display: "flex", gap: 6, marginBottom: 8 },
  kindBtn: { flex: 1, border: `1px solid ${LINE}`, background: "var(--card-bg)", borderRadius: 10, padding: "9px 4px", fontSize: 13.5, fontWeight: 700, cursor: "pointer", color: INK, fontFamily: "inherit" },
  fieldLabel: { display: "block", fontSize: 12, color: MUTED, fontWeight: 700, margin: "12px 2px 6px" },
  amountWrap: { display: "flex", alignItems: "center", background: "var(--card-bg)", border: `1.5px solid ${ACCENT}`, borderRadius: 12, padding: "6px 14px" },
  yenMark: { fontSize: 22, color: MUTED, marginRight: 6 },
  amountInput: { flex: 1, border: "none", outline: "none", fontSize: 28, fontWeight: 800, background: "transparent", color: INK, width: "100%", fontFamily: "inherit" },
  signHint: { fontSize: 11.5, color: MUTED, margin: "6px 2px 0" },
  salaryRow: { display: "flex", alignItems: "center", gap: 10, marginBottom: 10 },
  takeHomeRow: { display: "flex", justifyContent: "space-between", alignItems: "center", padding: "12px 2px 0", marginTop: 4, borderTop: `1px solid ${LINE}`, fontSize: 14, fontWeight: 700 },
  optionRow: { display: "flex", flexWrap: "wrap", gap: 6, marginBottom: 8 },
  typeRow: { display: "flex", gap: 6, marginBottom: 8, overflowX: "auto", paddingBottom: 2, WebkitOverflowScrolling: "touch" },
  typeChip: { flexShrink: 0, border: `1px solid ${LINE}`, background: "var(--card-bg)", borderRadius: 20, padding: "6px 12px", fontSize: 12.5, cursor: "pointer", color: INK, fontFamily: "inherit", whiteSpace: "nowrap" },
  optionChip: { border: `1px solid ${LINE}`, background: "var(--card-bg)", borderRadius: 20, padding: "6px 13px", fontSize: 13, cursor: "pointer", color: INK, fontFamily: "inherit" },
  optionChipActive: { background: ACCENT, color: "#fff", border: `1px solid ${ACCENT}` },
  textInput: { width: "100%", border: `1px solid ${LINE}`, borderRadius: 10, padding: "10px 12px", fontSize: 15, outline: "none", background: "var(--card-bg)", color: INK, boxSizing: "border-box", fontFamily: "inherit" },
  flash: { background: ACCENT_SOFT, color: ACCENT, borderRadius: 10, padding: "9px 12px", fontSize: 13, fontWeight: 600, marginBottom: 10 },
  saveBtn: { width: "100%", border: "none", background: ACCENT, color: "#fff", borderRadius: 12, padding: "14px", fontSize: 15, fontWeight: 800, cursor: "pointer", marginTop: 18, fontFamily: "inherit" },
  saveBtnHalf: { flex: 1, border: "none", background: ACCENT, color: "#fff", borderRadius: 12, padding: "13px 8px", fontSize: 13.5, fontWeight: 800, cursor: "pointer", fontFamily: "inherit" },
  deleteBtn: { width: "100%", border: "none", background: "transparent", color: RED, borderRadius: 12, padding: "12px", fontSize: 13.5, cursor: "pointer", marginTop: 4, fontFamily: "inherit" },
  cancelBtn: { width: "100%", border: "none", background: "transparent", color: MUTED, borderRadius: 12, padding: "10px", fontSize: 13.5, cursor: "pointer", fontFamily: "inherit" },
};


if (typeof document !== "undefined" && !document.getElementById("kakeibo-kf")) {
  const s = document.createElement("style"); s.id = "kakeibo-kf";
  s.textContent = "@keyframes slideUp{from{transform:translateY(100%)}to{transform:translateY(0)}}";
  document.head.appendChild(s);
}
